services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelant\PxaFormEnhancement\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Pixelant\PxaFormEnhancement\Domain\Finishers\SaveFormFinisher:
    public: true
